import { useState } from 'react'
import { supabase } from '../lib/supabase'
import { useNavigate } from 'react-router-dom'

// All eight files required by HMRC's service recognition process.
// Files are labelled exactly as HMRC's recognition document v1.7 describes them.
const FILE_LABELS: Record<string, { label: string; who: string }> = {
  'R68_submission.xml':            { label: 'R68 Submission',            who: 'Generated by software (with GatewayTimestamp for LTS/recognition)' },
  'SUBMISSION_ACKNOWLEDGEMENT.xml':{ label: 'Submission Acknowledgement', who: 'Returned by HMRC Transaction Engine' },
  'SUBMISSION_POLL.xml':           { label: 'Submission Poll',            who: 'Generated by software' },
  'SUBMISSION_RESPONSE.xml':       { label: 'Submission Response',        who: 'Returned by HMRC Transaction Engine' },
  'DELETE_REQUEST.xml':            { label: 'Delete Request',             who: 'Generated by software' },
  'DELETE_RESPONSE.xml':           { label: 'Delete Response',            who: 'Returned by HMRC Transaction Engine' },
  'DATA_REQUEST.xml':              { label: 'Data Request',               who: 'Generated by software' },
  'DATA_RESPONSE.xml':             { label: 'Data Response',              who: 'Returned by HMRC Transaction Engine' },
}

function Logo() {
  return (
    <span style={{ fontFamily: "'Poppins', sans-serif", fontWeight: 800, color: '#0c745d', fontSize: '1.6rem', lineHeight: 1 }}>
      gift aided <span style={{ fontWeight: 400 }}>Portal</span>
    </span>
  )
}

function downloadXml(filename: string, content: string) {
  const blob = new Blob([content], { type: 'application/xml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

export default function RecognitionPackage() {
  const navigate = useNavigate()
  const [submissionId, setSubmissionId] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)

  const loadFiles = async () => {
    if (!submissionId.trim()) { setError('Enter a submission ID.'); return }
    setLoading(true); setError(null); setResult(null)
    try {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) { navigate('/login'); return }
      const resp = await fetch(`/api/admin/exportRecognitionPackage?submission_id=${submissionId.trim()}`, {
        headers: { Authorization: `Bearer ${session.access_token}` },
      })
      const json = await resp.json()
      if (!resp.ok || !json.ok) throw new Error(json.error || 'Failed to load files')
      setResult(json)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  const downloadAll = () => {
    if (!result?.files) return
    Object.entries(result.files as Record<string, string | null>).forEach(([filename, content]) => {
      if (content) downloadXml(filename, content)
    })
  }

  return (
    <div className="min-h-screen bg-brand-surface">
      <nav className="bg-white border-b border-gray-100">
        <div className="w-full px-8 py-4 flex justify-between items-center">
          <Logo />
          <button onClick={async () => { await supabase.auth.signOut(); navigate('/login') }}
            className="text-sm text-gray-400 hover:text-gray-600 transition-colors">Log Out</button>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 pt-12 pb-12">
        <button onClick={() => navigate('/admin')} className="text-sm font-medium text-brand-accent hover:underline mb-4 inline-block">← Back to Admin</button>
        <h1 className="text-3xl font-bold text-brand-primary">HMRC Recognition Package</h1>
        <p className="text-gray-400 text-sm mt-2 max-w-xl">
          Export the eight XML files required for HMRC's Charities Online service recognition process. Enter the submission ID of the completed ETS test submission to retrieve all files.
        </p>

        <div className="mt-8 bg-white rounded-xl border border-gray-100 shadow-sm p-6 space-y-4">
          <div>
            <label className="block text-xs font-semibold text-gray-400 uppercase tracking-wide mb-1">Submission ID</label>
            <div className="flex gap-3">
              <input
                type="text"
                value={submissionId}
                onChange={e => setSubmissionId(e.target.value)}
                placeholder="Paste the submission UUID from the admin panel"
                className="flex-1 text-sm border border-gray-200 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-brand-accent/30 font-mono"
              />
              <button
                onClick={loadFiles}
                disabled={loading}
                className="bg-brand-accent text-white rounded-lg px-4 py-2 text-sm font-semibold hover:opacity-90 disabled:opacity-40"
              >
                {loading ? 'Loading…' : 'Load Files'}
              </button>
            </div>
            <p className="text-xs text-gray-300 mt-1">
              Find the ID by clicking into a submission's detail page — it's the UUID in the URL.
            </p>
          </div>

          {error && <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded text-sm">{error}</div>}
        </div>

        {result && (
          <div className="mt-6 space-y-4">
            <div className={`rounded-xl border p-4 text-sm ${result.readyToSubmit ? 'bg-green-50 border-green-200 text-green-700' : 'bg-amber-50 border-amber-200 text-amber-700'}`}>
              <p className="font-semibold mb-1">{result.readyToSubmit ? '✓ All 8 files ready' : `${result.missing.length} file(s) still missing`}</p>
              <p>{result.message}</p>
            </div>

            {result.readyToSubmit && (
              <button
                onClick={downloadAll}
                className="w-full bg-brand-accent text-white rounded-lg px-4 py-3 text-sm font-semibold hover:opacity-90"
              >
                Download All 8 Files
              </button>
            )}

            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="px-6 py-4 border-b border-gray-50">
                <h2 className="font-semibold text-brand-primary">Tax year {result.taxYear} · Status: {result.hmrcStatus}</h2>
              </div>
              <div className="divide-y divide-gray-50">
                {Object.entries(FILE_LABELS).map(([filename, meta]) => {
                  const content = result.files[filename] as string | null
                  return (
                    <div key={filename} className="px-6 py-4 flex items-center justify-between gap-4">
                      <div className="min-w-0">
                        <p className="text-sm font-medium text-brand-primary">{filename}</p>
                        <p className="text-xs text-gray-400 mt-0.5">{meta.who}</p>
                      </div>
                      {content ? (
                        <button
                          onClick={() => downloadXml(filename, content)}
                          className="flex-shrink-0 text-xs font-semibold text-brand-accent hover:text-brand-primary"
                        >
                          Download
                        </button>
                      ) : (
                        <span className="flex-shrink-0 text-xs font-semibold text-red-400">Missing</span>
                      )}
                    </div>
                  )
                })}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
